x-extends:
  x11: &x11  # Create 'x11' aliases that can be referenced using '*x11'
    extends:
      file: docker/common.yaml
      service: x11_base
    profiles: [optional]

  base: &base
    extends:
      file: docker/common.yaml
      service: base
    profiles: [optional]


services:
  compile:
    <<: *base
    environment:  # remove annoying warning of setuptools
      - PYTHONWARNINGS=ignore:::setuptools.command.easy_install
    command: 'colcon --log-base /dev/null build --symlink-install --event-handlers event_log- log-'

  compile_with_log:
    <<: *base
    environment:  # remove annoying warning of setuptools
      - PYTHONWARNINGS=ignore:::setuptools.command.easy_install
    command: 'colcon build --symlink-install'

  bash:
    <<: *x11
    command: 'bash --rcfile /etc/bash.bashrc'

  adap2e_test:
    <<: *x11
    command: 'ros2 launch adap2e_bringup adap2e_test.launch.py'

  alpo_test:
    <<: *x11
    command: 'ros2 launch alpo_bringup alpo_test.launch.py'
    
  ceol_test:
    <<: *x11
    command: 'ros2 launch ceol_bringup ceol_test.launch.py'
    
  robufast_test:
    <<: *x11
    command: 'ros2 launch robucar_bringup robucar_test.launch.py'

  path_following:
    <<: *x11
    command: >-
      ros2 launch tirrex_path_following path_following.launch.py
        robot:=adap2e path:=field.txt
