version: '3.4'
services:
  compile:
    build:
      context: docker/
      target: dever
      ssh: [default]
      args:
        - USER=$USER
        - UID=$UID
        - GID=$GID
        - HOME=$HOME
        - REPOS_FILE=${REPOS_FILE:-repositories}
      #   - FROM_IMAGE=osrf/ros:galactic-desktop
    image: tirrex_fira:devel
    extends:
      file: docker/common.yml
      service: base
    command: 'colcon build --symlink-install'

  bash:
    image: tirrex_fira:devel
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'bash'

  adap2e_test:
    image: tirrex_fira:devel
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch adap2e_bringup adap2e_test.launch.py mode:=live'

  adap2e:
    image: tirrex_fira:devel
    extends:
      file: docker/common.yml
      service: x11_base
    depends_on:
      compile:
        condition: service_completed_successfully
    command: 'ros2 launch tirrex_adap2e adap2e.launch.py mode:=live localisation:=false'
