services:
  compile:
    build:
      context: docker/
      target: dever
      ssh: [default]
      args:
        - USER=$USER
        - UID=$UID
        - GID=$GID
        - HOME=$HOME
        - REPOS_FILE=${REPOS_FILE:-repositories}
      #   - FROM_IMAGE=osrf/ros:galactic-desktop
    extends:
      file: docker/common.yml
      service: base
    command: 'colcon build --symlink-install'

  bash:
    extends:
      file: docker/common.yml
      service: x11_base
      # service: x11_gpu
    command: 'bash'

  adap2e_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch adap2e_bringup adap2e_test.launch.py'
    
  campero_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch campero_bringup campero_test.launch.py'
    
  ceol_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch ceol_bringup ceol_test.launch.py'
    
  cinteo_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch cinteo_bringup cinteo_test.launch.py'
  
  hunter_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch hunter_bringup hunter_test.launch.py'

  husky_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch husky_bringup husky_test.launch.py'
    
  scout_mini_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch scout_bringup scout_test.launch.py model:=mini'
    
  robufast_test:
    extends:
      file: docker/common.yml
      service: x11_base
    command: 'ros2 launch robucar_bringup robucar_test.launch.py'
