version: '3.4'
services:
  compile:
    build:
      context: docker/
      target: dever
      ssh: [default]
      # args:
      #   - FROM_IMAGE=osrf/ros:galactic-desktop
    image: tirrex_fira:devel
    extends:
      file: docker/common.yml
      service: base
    command: 'colcon build --symlink-install'

  adap2e_test:
    image: tirrex_fira:devel
    extends:
      file: docker/common.yml
      service: x11_base
      # service: x11_gpu  # use this one if you want to use the GPU
    depends_on:
      compile:
        condition: service_completed_successfully
    command: 'ros2 launch adap2e_bringup adap2e_test.launch.py'
