services:
  devel:
    image: gitlab-registry.irstea.fr/romea_projects/tirrex/tirrex_workspace:hackathon
    build:
      context: .
      target: dever
      ssh: [default]
      args:
        - REPOS_FILE=${REPOS_FILE:-repositories.private}
      #   - FROM_IMAGE=osrf/ros:galactic-desktop
