services:
  base:
    build: # use tirrex_workspace image but add the host user in it
      dockerfile_inline: |
        FROM gitlab-registry.irstea.fr/romea_projects/tirrex/tirrex_workspace:devel
        RUN groupadd -g ${GID-} $USER && \
            useradd -u ${UID-} -g ${GID-} -s /bin/bash -d $HOME -G dialout $USER
    image: tirrex_workspace
    volumes:
      - $PWD:$PWD
    environment:
      - WORKSPACE=$PWD
      - USER
      - ROS_LOCALHOST_ONLY=1  # avoid sending multicast on the local network of your office
    network_mode: host
    pid: host  # fix a multicast problem, PID are used by DDS to generate unique GUID
    ipc: host  # also used by ROS2
    privileged: true

  x11_base:
    extends:
      service: base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
      - $HOME:$HOME
    environment:
      - DISPLAY
      - XDG_RUNTIME_DIR
      - GAZEBO_RESOURCE_PATH=$PWD/gazebo
      - GAZEBO_MODEL_PATH=$PWD/gazebo/models
      - GAZEBO_TEST=$PWD/gazebo/models
    devices:
      - /dev/input/  # for joypads
  
  x11_gpu:
    extends:
      service: base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
      - $HOME:$HOME
    environment:  # these variables allows to use the GPU when the nvidia profile is 'on-demand'
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
      - XDG_RUNTIME_DIR
      - GAZEBO_RESOURCE_PATH=$PWD/gazebo
      - GAZEBO_MODEL_PATH=$PWD/gazebo/models
      - GAZEBO_TEST=$PWD/gazebo/models
    devices:
      - /dev/input/  # for joypads
      - /dev/dri/    # for graphic card
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
