version: '3.4'
services:
  base:
    volumes:
      - $PWD:$PWD
    environment:
      - WORKSPACE=$PWD
      - USER
      # - ROS_LOCALHOST_ONLY=1  # avoid sending multicast on the local network of your office
    # devices:
    #   - /dev/input/  # for joypads
    #   - /dev/dri/    # for graphic card
    network_mode: host
    pid: host  # fix a multicast problem, PID are used by DDS to generate unique GUID
    ipc: host  # also used by ROS2
    privileged: true

  x11_base:
    extends:
      service: base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
      - $HOME:$HOME
    environment:
      - DISPLAY
      - XDG_RUNTIME_DIR
      - GAZEBO_RESOURCE_PATH=$PWD/gazebo
      - GAZEBO_MODEL_PATH=$PWD/gazebo/models
      - GAZEBO_TEST=$PWD/gazebo/models
    devices:
      - /dev/input/  # for joypads
      - /dev/dri/    # for graphic card
    # privileged: true
  
  x11_gpu:
    extends:
      service: x11_base
    environment:  # these variables allows to use the GPU when the nvidia profile is 'on-demand'
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  zed_req:
    extends:
      service: x11_gpu
    volumes:
      - /usr/local/zed/resources:/usr/local/zed/resources
      - /usr/local/zed/settings:/usr/local/zed/settings
      - /usr/local/zed/tools:/usr/local/zed/tools
      - /dev:/dev
