x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ../../docker/common.yaml
      service: x11_base
      # service: x11_gpu  # use this service if you want to use nvidia GPU
    volumes:
      - ./config:/config
      # - /tmp:/tmp  # uncomment to read generated files in /tmp


services:
  bash:
    <<: [*base]  # add elements of 'x-yaml-anchors.base'
    profiles: [no]  # avoid starting this service when 'compose up'
    command: bash --rcfile /etc/bash.bashrc

  simulator:
    <<: [*base]
    command: >-
      ros2 launch tirrex_demo demo.launch.py
        demo_config_directory:=/config
        mode:=simulation_gazebo_classic
        robot_namespace:=robot
        localisation:=false
        record:=false
        demo:=hackathon
        demo_timestamp:=%F_%T
