x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ../../docker/common.yaml
      service: x11_base
      # service: x11_gpu  # use this service if you want to use nvidia GPU
    volumes:
      - ./config:/config
      # - /tmp:/tmp  # uncomment to read generated files in /tmp


services:
  bash:
    <<: [*base]  # add elements of 'x-yaml-anchors.base'
    profiles: [no]  # avoid starting this service when 'compose up'
    command: bash --rcfile /etc/bash.bashrc

  simulator:
    <<: [*base]
    command: >-
      ros2 launch hackathon_bringup simulator.launch.py
        demo_config_directory:=/config
        mode:=simulation_gazebo_classic
        robot_namespace:=robot

  localisation:
    <<: [*base]
    command: >-
      ros2 launch tirrex_demo robot_localisation.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        mode:=simulation_gazebo_classic
        robot_namespace:=robot

  path_following:
    <<: [*base]
    command: >-
      ros2 launch tirrex_demo robot_path_recorder.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        mode:=simulation_gazebo_classic
        robot_namespace:=robot
        trajectory_filename:=challenge.traj

  path_recorder:
    <<: [*base]
    command: >-
      ros2 launch tirrex_demo robot_path_recorder.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        mode:=simulation_gazebo_classic
        robot_namespace:=robot
        trajectory_filename:=/config/paths/recorded.traj
