name: "base"
configuration:
  type: adap2e
  model: fat
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  initial_xyz: [135.315, 134.135, 0.88]
  initial_rpy: [0.0, 0.0, -2.825]
