name: "base"
configuration:
  type: adap2e
  model: fat
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  initial_xyz: [107.795, 123.508, 1.15]
  initial_rpy: [0.014, 0.021, 0.372]
